services:
    live:
        public: true
        container_name: android-container
        image: qeeqbox/android-tools:1.0
        ports:
            - 6080:6080
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
