services:
    live:
        public: true
        container_name: go
        image: chenjr0719/ubuntu-mate-novnc:latest
        ports:
            - 8080:6080
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
