services:
    live:
        public: true
        container_name: go
        image: chenjr0719/ubuntu-mate-novnc:latest
        ports:
            - 80:6080
        environment:
            - PASSWORD=123456
            - SUDO=yes
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
