services:
    live:
        public: true
        container_name: android-container
        image: budtmo/docker-android-x86-8.1
        ports:
            - 6080:6080
            - 5554:5554
            - 8080:8080
        volumes:
            - /mnt/restreamer/db:/restreamer/db
        environment:
            - DEVICE="Samsung Galaxy S6"
            - RS_PASSWORD=mjy@@1381
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
