services:
    live:
        public: true
        container_name: go
        image: accetto/ubuntu-vnc-xfce:latest
        ports:
            - 5901:5901
        volumes:
            - /home/headless/Documents/
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
