services:
    ubuntu:
        public: true
        container_name: 13131
        image: qeeqbox/parrot:1.0
        ports:
            - 6080:6080
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
