services:
    ubuntu:
        public: true
        container_name: 13131
        image: accetto/ubuntu-vnc-xfce:latest
        ports:
            - 6901:6901
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 6000Mi
          storage:
            size: 10Gi
            class: standard
