services:
    ubuntu:
        public: true
        container_name: 13131
        image: accetto/ubuntu-vnc-xfce:latest
        ports:
            - 6901:6901
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 4072Mi
          storage:
            size: 5Gi
            class: standard
